### ISSUE TITLE
zoeken op huisletter en huisnummertoevoeging case insensitive

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#100]
/wozobjecten?postcode=8000GB&huisnummer=1&huisletter=L&huisnummertoevoeging=toev geeft me een WOZ-object

/wozobjecten?postcode=8000GB&huisnummer=1&huisletter=l&huisnummertoevoeging=toev geeft een lege collectie
/wozobjecten?postcode=8000GB&huisnummer=1&huisletter=L&huisnummertoevoeging=TOEV geeft een lege collectie

Ik denk dat gebruikers vaak niet weten of in het adres de huisletter of huisnummertoevoeging met hoofdletter of kleine letter(s) geschreven is. Daarom zou ik het gebruikersvriendelijker vinden dat zoeken op huisletter en huisnummertoevoeging case insensitive is.

N.B. bij zoeken in BAG, BRK en BRP is zoeken op huisletter en huisnummertoevoeging ook case insensitive.

**Comment by kad-tromps** [comment]
Gaan we fixen
