### ISSUE TITLE
meerdere fouten tegelijk allemaal tonen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#101]
Wanneer er in een request meerdere fouten tegelijkertijd zijn gemaakt, is het vriendelijk voor de gebruiker die ook allemaal tegelijk te tonen. Dan kan de gebruiker in één keer alle fouten oplossen, zodat de volgende poging van de gebruiker niet weer een foutmelding geeft. Op dit moment wordt alleen de eerste fout getoond.

Bijvoorbeeld bij foute postcode en fout huisnummer /wozobjecten?postcode=1&huisnummer=1234AB krijg ik alleen de foutmelding over de postcode:
```
    "detail": "Parameter 'postcode' bevat een (deels) ongeldige waarde",
    "invalidParams": [
        {
            "code": "pattern",
            "reason": "Waarde voldoet niet aan het patroon ^[0-9]{4}[a-zA-Z]{2}$",
            "name": "postcode"
        }
    ]
```

Bijvoorbeeld bij fout kvkNummer en foute pageSize /wozobjecten?kvkNummer=1234567A&pageSize=0
```
    "invalidParams": [
        {
            "reason": "De parameter 'pageSize' moet groter zijn dan 0.",
            "code": "page",
            "name": "page"
        }
    ]
```

**Comment by fsamwel** [comment]
@kad-leenec Dit gedrag zouden we wel graag zien. Zie de volgende rule en scenario in https://github.com/VNG-Realisatie/Haal-Centraal-WOZ-bevragen/blob/master/features/fout-meldingen.feature

Rule: alle parameter fouten in een request worden samen geretourneerd

```
    Scenario: er zijn meerdere verschillende fout soorten
    Als '/wozobjecten?rsin=abc&fields=bestaatniet' wordt aangeroepen
    Dan bevat de response de volgende kenmerken
        | naam   | waarde                                                                                                                                                                                |
        | title  | Een of meerdere parameters zijn niet correct.                                                                                                                   |
        | status | 400                                                                                                                                                                                   |
        | detail | Alleen parameter 'adresseerbaarObjectIdentificatie' of 'nummeraanduidingIdentificatie' moet zijn opgegeven.<br />Parameters 'fields', 'expand' bevatten een (deels) ongeldige waarde. |
    En bevat de response de volgende invalidParams
        | name   | reason                                    |
        | rsin   | waarde 'A' is geen 9 cijferig getal       |
        | fields | ongeldige waarde: 'bestaatniet' opgegeven |
```
In dit voorbeeld zijn er twee foute parameters, dus moeten er twee invalidParams worden gegeven en moeten beide foute parameters worden genoemd in detail

**Comment by kad-tromps** [comment]
@fsamwel Er is een fout mogelijk bij de zoekingang als er een verkeerde combinatie van parameters wordt opgegeven, zoals beschreven bij de code unsupportedCombi in https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/foutafhandeling.feature. Dit is echter, voor zover ik dat kan interpreteren, een top level fout, op het zelfde niveau als de invalidParams fout. Nu kan het voorkomen dat je een verkeerde combinatie van parameters hebt opgegeven EN een of meerdere verkeerde parameters hebt opgegeven:

`haalcentraal.url/wozobjecten?rsin=a&kvkNummer=b`

Hoe willen jullie deze twee fouten met elkaar afgehandeld zien? Persoonlijk zit ik te denken om van unsupportedCombi ook een invalidParam te maken, zonder `name` veld:

```
  {
      "type": "https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1",
      "title": "Een of meerdere parameters zijn niet correct.",
      "instance": "http://localhost:8080/wozobjecten?rsin=a&kvkNummer=b",
      "status": 400,
      "invalidParams": [
          {
            "code": "pattern",
            "reason": "Waarde voldoet niet aan het patroon ^[0-9]{9}$",
            "name": "rsin"
          },
         {
            "code": "pattern",
            "reason": "Waarde voldoet niet aan het patroon ^[0-9]{8}$",
            "name": "kvkNummer"
        },
        {
            "code": "unsupportedCombi",
            "reason": "De combinatie van opgegeven parameters is niet toegestaan""
        }
      ]
  }
```

Wat denken jullie hier over?

**Comment by kad-tromps** [comment]
@fsamwel Vorige foutmeldingen voor bijvoorbeeld RSIN hadden in de hoofd foutmelding nog een `details` veld, met daar in "Parameter 'rsin' bevat een (deels) ongeldige waarde". Nu we meerdere foutmeldingen tonen is dit niet meer logisch, aangezien er meerdere dingen fout kunnen zijn. Willen jullie een samenvatting van de `invalidParams` in het `details` veld? Of kan het details veld weg gelaten worden voor de `Een of meerdere parameters zijn niet correct.` fout?

**Comment by fsamwel** [comment]
@kad-tromps 

>  Willen jullie een samenvatting van de invalidParams in het details veld? Of kan het details veld weg gelaten worden voor de Een of meerdere parameters zijn niet correct. fout?

Maak het niet te complex. als er één of meerdere parameters onjuist zijn, kan je ze in details opsommen. Wanneer er verschillende soorten fouten zijn, dan de eerste tonen. Ik denk dat @MelvLee had aangegeven liever eerst de invalidParams te krijgen boven parameter combinatie.

> Persoonlijk zit ik te denken om van unsupportedCombi ook een invalidParam te maken

Mijn interpretatie is dat invalidParams alleen per echte parameter gemeld moet worden, zodat je deze meldingen kunt koppelen aan specifieke parameters. Onjuiste parametercombinatie en parameter validatie fouten kun je dus niet combineren in één foutmelding

**Comment by fsamwel** [comment]
Zie pull request https://github.com/VNG-Realisatie/Haal-Centraal-WOZ-bevragen/pull/117 waarin het vullen van het detail veld i.c.m. invalidParams is uitgewerkt
