### ISSUE TITLE
huisnummer, page en pageSize hebben minimum en maximum waarden

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#102]
```
huisnummer is gedefinieerd als:
          maximum: 99999
          minimum: 1
          type: integer
```

/wozobjecten?postcode=1234AB&huisnummer=0 geeft een lege collectie, geen foutmelding
/wozobjecten?postcode=1234AB&huisnummer=100000 geeft een lege collectie, geen foutmelding

```
page is gedefinieerd als:
          minimum: 1
          type: integer
          default: 1
```

/wozobjecten?postcode=8000GB&huisnummer=1&pageSize=0 geeft foutmelding, maar in invalidParams staat "code": "page". Hier had ik "code": "minimum" verwacht

/wozobjecten?postcode=8000GB&huisnummer=1&page=0 geeft foutmelding "De opgegeven pagina bestaat niet.", maar het request voldoet niet aan de specificaties, dus ik had een foutmelding verwacht die zich hierop richt.

```
pageSize is gedefinieerd als:
          maximum: 100
          minimum: 1
          type: integer
          default: 20
```

/wozobjecten?postcode=8000GB&huisnummer=1&pageSize=101 levert gevonden wozobjecten, maar het request voldoet niet aan de specificaties, dus ik had een foutmelding verwacht die zich hierop richt.

**Comment by fsamwel** [comment]
@MelvLee kan jij voor deze situaties ook de foutafhandeling feature doorkijken of die hierin beschreven staan?

**Comment by MelvLee** [comment]
> 
> 
> @MelvLee kan jij voor deze situaties ook de foutafhandeling feature doorkijken of die hierin beschreven staan?

fout-meldingen feature is aangevuld. Zie: https://github.com/VNG-Realisatie/Haal-Centraal-WOZ-bevragen/pull/109

**Comment by fsamwel** [comment]
De validatie bij pageSize is nu niet correct. Ik krijg nu:
```
{
    "type": "https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1",
    "title": "Een of meerdere parameters zijn niet correct.",
    "instance": "http://api.acceptatie.kadaster.nl/haalcentraal-api/wozobjecten?postcode=8000GB&huisnummer=1&pageSize=101",
    "status": 400,
    "invalidParams": [
        {
            "code": "maxLength",
            "reason": "Waarde is langer dan maximale lengte 100",
            "name": "pageSize"
        }
    ],
    "code": "paramsValidation"
}
```
pageSize moet een integer zijn en heeft een maximale waarde. De invoer pageSize=101 is niet langer dan maximale lengte 100, maar is groter dan de toegestane waarde. zie ook https://github.com/VNG-Realisatie/Haal-Centraal-WOZ-bevragen/blob/master/features/fout-meldingen.feature regel 111

zelfde gebeurt in page.

https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten?postcode=8000GB&huisnummer=1&page=0 geeft    
```
"invalidParams": [
        {
            "code": "minLength",
            "reason": "Waarde is korter dan minimale lengte 1",
            "name": "page"
        }
    ],
```
Ik had verwacht
```
"invalidParams": [
        {
            "code": "minimum",
            "reason": "Waarde '0' is kleiner dan de toegestane minimum waarde (1)",
            "name": "page"
        }
    ],
```

**Comment by kad-tromps** [comment]
gaan we aanpassen

**Comment by melsk-r** [comment]
> /wozobjecten?postcode=1234AB&huisnummer=0 geeft een lege collectie, geen foutmelding
Is opgelost, er wordt nu wel een foutmelding teruggegeven.

> /wozobjecten?postcode=1234AB&huisnummer=100000 geeft een lege collectie, geen foutmelding
Is opgelost, er wordt nu wel een foutmelding teruggegeven.

> /wozobjecten?postcode=8000GB&huisnummer=1&pageSize=0 geeft foutmelding, maar in invalidParams staat "code": "page". Hier had ik "code": "minimum" verwacht
Is opgelost, er wordt nu wel de juiste code teruggegeven.

> /wozobjecten?postcode=8000GB&huisnummer=1&page=0 geeft foutmelding "De opgegeven pagina bestaat niet.", maar het request voldoet niet aan de specificaties, dus ik had een foutmelding verwacht die zich hierop richt.
Is opgelost, er wordt nu wel een foutmelding gegeven die zich op de specificaties richt.

> /wozobjecten?postcode=8000GB&huisnummer=1&pageSize=101 levert gevonden wozobjecten, maar het request voldoet niet aan de specificaties, dus ik had een foutmelding verwacht die zich hierop richt.
Is opgelost, er wordt nu wel een foutmelding gegeven die zich op de specificaties richt.

> De validatie bij pageSize is nu niet correct.
De 'invalidParams' lijkt nu correct te zijn, nu krijgen we:
```
    "invalidParams": [
        {
            "code": "maximum",
            "reason": "waarde '101' is groter dan de toegestane maximum waarde (100)",
            "name": "pageSize"
        }
```

Ook de 'invalidParams' bij https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten?postcode=8000GB&huisnummer=1&page=0 is nu correct.
