### ISSUE TITLE
detail ontbreekt in foutmelding bij onjuiste page parameter waarde

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#103]
/wozobjecten?postcode=8000GB&huisnummer=1&page=0

geeft terecht een foutmelding. Hierin ontbreekt detail (wordt in de andere foutsituaties wel opgenomen)

```
{
    "type": "https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1",
    "title": "Een of meerdere parameters zijn niet correct.",
    "instance": "http://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten?postcode=8000GB&huisnummer=1&page=0",
    "status": 400,
    "invalidParams": [
        {
            "reason": "De opgegeven pagina bestaat niet.",
            "code": "page",
            "name": "page"
        }
    ]
}
```

**Comment by kad-tromps** [comment]
@fsamwel details staan niet gedefinieerd in de feature waar deze foutmelding is gedefinieerd https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/paginering.feature

**Comment by fsamwel** [comment]
@kad-tromps de foutafhandeling hiervoor staat beschreven in https://github.com/VNG-Realisatie/Haal-Centraal-WOZ-bevragen/blob/master/features/fout-meldingen.feature. 
Daarin staat op regel 97: | detail | Parameter 'page' bevat een (deels) ongeldige waarde |

**Comment by kad-tromps** [comment]
Volgensmij hebben we besproken dat we dit detail achterwegen zouden laten. De details zijn af te leiden in de lijst met invalid parameters, en als er meerder fouten in het request zijn, moeten we deze in het detail veld generiek gaan samen plakken om een correcte nederlandse foutmelding te genereren, wat meer moeite is dan het waard is. Ik zal kijken of ik deze dialoog kan vinden.

**Comment by melsk-r** [comment]
> Daarin staat op regel 97: | detail | Parameter 'page' bevat een (deels) ongeldige waarde |

@fsamwel Ik zie op regel 97 niet dat wat jij hier beschrijft.

@kad-tromps Had je dialoog nog kunnen vinden?

**Comment by kad-verstp** [comment]
@melsk-r  @fsamwel @kad-tromps 
Op dit moment bij een ongeldige parameter is dit het response:

{
    "type": "https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1",
    "title": "Tenminste één parameter moet worden opgegeven.",
    "detail": "Er moet minimaal één van de parameters 'rsin', 'kvkNummer', 'adresseerbaarObjectIdentificatie', 'nummeraanduidingIdentificatie' of 'postcode' met 'huisnummer' worden opgegeven",
    "instance": "https://lvwoz-router.fto.kadaster.nl/lvwoz/api/v1/wozobjecten?%3Cparameter%3E=123456789",
    "status": 400,
    "code": "unsupportedCombi"
