### ISSUE TITLE
Baseurl van _links.self niet correct

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#123]
De operatie GET https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten/nnnnnnnnnnnn 
geeft als _links.self.href terug ‘http://api.acceptatie.kadaster.nl/haalcentraal-api/wozobjecten/nnnnnnnnnnnn’.
Ik zou echter dezelfde link terug verwachten als waar ik het request naar doe.

**Comment by melsk-r** [comment]
Bij de operatie 'GET https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten?postcode=8000GB&huisnummer=1&huisletter=L&huisnummertoevoeging=toev' waarvoor bovenstaande opmerking ook geldt is nog iets vreemds aan de hand.

Daar krijg ik in ‘_links.self.href’ de waarde 'http://api.acceptatie.kadaster.nl/haalcentraal-api/wozobjecten?postcode=8000GB&huisnummer=1&huisletter=L&huisnummertoevoeging=toev'. Ik had echter niet verwacht daarin de request parameters 'postcode', 'huisnummer', 'huisletter' en 'huisnummertoevoeging' te zien.

**Comment by melsk-r** [comment]
Het kan zijn dat dit issue al is beschreven in https://github.com/VNG-Realisatie/Haal-Centraal-WOZ-bevragen/issues/59.

**Comment by CathyDingemanse** [comment]
@JohanBoer @melsk-r de WOZ API is in productie en wordt gebruikt! In eerste instantie alleen voor belastingheffing.
De gemeente Den Haag is aangesloten en gebruikt de API hier ook voor.

**Comment by fsamwel** [comment]
wij moeten niet acceptatie, maar de eto omgeving gebruiken.

Als ik GET https://api.kadaster.nl/lvwoz-eto/huidigebevragingen/wozobjecten/800000051111 doe,

krijg ik
```
    "_links": {
        "self": {
            "href": "https://api.kadaster.nl/lvwoz-eto/huidigebevragingen/wozobjecten/800000051111"
        },
```

issue is dus opgelost

**Comment by JohanBoer** [comment]
@CathyDingemanse  dank voor het aanscherpen. Het was mij even ontschoten dat Den Haag de API voor belastingheffing in gebruik heeft. 

@fsamwel Dank voor het testen. We hebben het zelf ook even geprobeerd (was allemaal ver weg gezakt,...) De self-link wijst nu inderdaad naar de eto. We sluiten de issue.
