### ISSUE TITLE
BaseUrl van instance property niet correct

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#124]
In operaties als GET https://api.acceptatie.kadaster.nl/lvwoz/api/v1//wozobjecten?postcode=1234 AB&huisnummer=1a die een foutmelding geven krijgt in die foutmelding de ‘ instance’  property een foutieve waarde, nl. iets beginnend met ‘http://api.acceptatie.kadaster.nl/haalcentraal-api/wozobjecten/….’.
Ik zou echter dezelfde link terug verwachten als waar ik het request naar doe.

**Comment by melsk-r** [comment]
Kan zijn dat dit issue gerelateerd is aan https://github.com/VNG-Realisatie/Haal-Centraal-WOZ-bevragen/issues/59.

**Comment by JohanBoer** [comment]
Zolang deze niet te testen is blijft deze open staan. Als de WOZ-APi beschikbaar wordt gesteld in productie, dan moet deze situatie getest worden.

**Comment by JohanBoer** [comment]
De operatie GET [https://api.kadaster.nl/lvwoz-eto/huidigebevragingen/wozobjecten?postcode=8000 GB&huisnummer=1](https://api.kadaster.nl/lvwoz-eto/huidigebevragingen/wozobjecten?postcode=8000%2520GB&huisnummer=1) geeft nu een foutmelding met als instance property: "https://api.kadaster.nl/lvwoz-eto/huidigebevragingen/wozobjecten?huisnummer=1&postcode=8000%2520GB"

Nu wordt dus de correct baseUrl gehanteerd.
