### ISSUE TITLE
url van ‘_links.{gerelateerde resource}.href’ incorrect?

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#125]
In de response van de operatie GET https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten/800000051111 heeft ‘_links.kadastraalOnroerendeZaken.href’ de waarde ‘https://api.brk.acceptatie.kadaster.nl/esd/bevragen/v1/kadastraalonroerendezaken/{kadastraalOnroerendeZaakIdentificaties}’

Volgens onze test in postman is deze waarde foutief (er wordt ‘https://api.brk.kadaster.nl/esd-eto-apikey/bevragen/v1/kadastraalonroerendezaken/{kadastraalOnroerendeZaakIdentificaties}’ verwacht), de vraag is echter of de test in postman incorrect is of dat er echt een verkeerde waarde wordt teruggegeven. In dat laatste geval is het trouwens nog steeds de vraag of de door postman verwachtte waarde wel de juiste is.

Iets soortgelijks speelt met 
* ‘_links.panden.href’ na de operatie https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten/800000051111. We verwachten de waarde https://api.bag.kadaster.nl/esd/huidigebevragingen/v1/panden/{pandIdentificaties} terwijl we https://api.bag.test.kadaster.nl/esd/huidigebevragingen/v1/panden/{pandIdentificaties} krijgen.
* ‘_links.panden.href’ na de operatie https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten?rsin=020664606
(zoeken op rsin/Eén object gevonden)
We verwachten de waarde https://api.bag.kadaster.nl/esd/huidigebevragingen/v1/panden/{pandIdentificaties} terwijl we https://api.bag.test.kadaster.nl/esd/huidigebevragingen/v1/panden/{pandIdentificaties} krijgen.
* ‘_links.adres.href’ na de operatie https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten/000500030828
(mapping/000500030828)
We verwachten de waarde https://api.bag.kadaster.nl/esd/huidigebevragingen/v1/adressen/0200200000098150 terwijl we https://api.bag.test.kadaster.nl/esd/huidigebevragingen/v1/adressen/0200200000098150 krijgen.
* ‘_links.kadastraalOnroerendeZaken.href’ na de operatie https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten?rsin=020664606
(zoeken op rsin/Eén object gevonden)
We verwachten de waarde https://api.brk.kadaster.nl/esd-eto-apikey/bevragen/v1/kadastraalonroerendezaken/{kadastraalOnroerendeZaakIdentificaties} terwijl we https://api.brk.acceptatie.kadaster.nl/esd/bevragen/v1/kadastraalonroerendezaken/{kadastraalOnroerendeZaakIdentificaties} krijgen.

**Comment by melsk-r** [comment]
Kan zijn dat dit issue gerelateerd is aan https://github.com/VNG-Realisatie/Haal-Centraal-WOZ-bevragen/issues/59.

**Comment by kad-tromps** [comment]
@melsk-r Externe links worden mee gegeven als configuratie. Volgensmij hebben we deze links toen de tijd van de api definitie gehaald, maar kan me vergissen. Als je me een lijstje van de verwachtte URLS voor de verschillende omgevingen geeft zal ik deze goed zetten
