### ISSUE TITLE
Waar kom de vreemde waarde in foutmelding vandaan?

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#135]
.../wozobjecten?postcode=8000GB&huisnummer=1&page=first levert de volgende invalidParams in de foutmelding op:

```
    "invalidParams": [
        {
            "code": "integer",
            "reason": "waarde 'first' is geen getal tussen 1 en 2147483647",
            "name": "page"
        }
    ]
```

Waar komt de waarde '2147483647' vandaan?

**Comment by kad-tromps** [comment]
Maximale integer waarde. Er is nooit een maximale waarde voor de page parameter gespecificeerd, dit is de default
