### ISSUE TITLE
Ter overweging: Start elke 'reason' met een hoofdletter

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#138]
De waarde van de 'reason' property in de foutberichten start soms met een hoofdletter en soms met een kleine letter. Overweeg om deze altijd met een hoofdletter te laten starten.

**Comment by kad-verstp** [comment]
@melsk-r @kad-tromps 
Ik zie "reason" altijd met een kleine letter staan. "code" en "name" en andere properties beginnen ook met een kleine letter
