### ISSUE TITLE
url in _links.adres niet correct

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#141]
De aanroep van `GET https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten/800000093455` geeft in '_links.adres' het volgende te zien:

`"href": "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adressen8513200000087078"`

Tussen 'adressen' en '8513200000087078' ontbreekt de '/'.

**Comment by fsamwel** [comment]
is nu correct
