### ISSUE TITLE
templated ontbreekt in link kadastraalOnroerendeZaken

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#147]
/wozobjecten/800000051111 geeft in _links:
```
        "kadastraalOnroerendeZaken": [
            {
                "href": "https://api.brk.acceptatie.kadaster.nl/esd/bevragen/v1/kadastraalonroerendezaken/{kadastraalOnroerendeZaken.identificatie}"
            }
        ],
```

deze link is templated, maar "templated": true ontbreekt (in andere templated links zoals panden zit dit wel)

**Comment by JohanBoer** [comment]
Op dit ogenblik worden de link als niet templated aangeboden. Issue speelt dus niet meer.
