### ISSUE TITLE
Inconsistentie in naamgeving

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#29]
In WozObjectHal is sprake van inconsistentie in naamgeving.
Naast de property 'belanghebbendeEigenaar' komt er in ' _links' de property 'belanghebbendEigenaar' voor en naast de property 'belanghebbendeGebruiker' komt er in ' _links' de property 'belanghebbendGebruiker'.

Maak deze aan elkaar gelijk.

**Comment by fsamwel** [comment]
is inmiddels opgelost
