### ISSUE TITLE
Oplossing voor belanghebbendeEigenaar.soort

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#35]
Uit de opmerking van @oversticht, zie https://github.com/VNG-Realisatie/Haal-Centraal-WOZ-bevragen/pull/34#discussion_r566972393, blijkt dat de LV niet in staat is de juiste omschrijving te leveren op basis van de codering.

De soort belanghebbendeEigenaar willen we eigenlijk als omschrijving leveren. Deze zou moeten worden samengesteld uit de codering voor Aard zakelijk recht. Die kan bestaan uit 1, 2 of 3 2-letter codes (dus een code van 2, 4 of 6 letters lang). De omschrijving van het soort zakelijk recht moet worden samengesteld door de omschrijvingen van de codes achter elkaar te plakken. 
Bijvoorbeeld code "PEOS" betekent "recht van erfpacht belast met recht van opstal".

Een oplossing kan zijn soort te definiëren als array voor elke deelcode. Bijvoorbeeld "PEOS" wordt dan "soort": ["PE", "OS"].

Liever dan de codes (zoals "EP"), zou ik meer begrijpelijke codering gebruiken, zoals "recht_van_erfpacht". Bijvoorbeeld "PEOS" wordt dan "soort": ["recht_van_erfpacht_belast_met", "recht_van_opstal"].

Wellicht nog beter (wanneer de gebruiker niet de code, maar de tekst wil) is de array items niet als enumeratie, maar als string te definiëren. "PEOS" wordt dan "soort": ["recht van erfpacht belast met", "recht van opstal"].

@oversticht:
- leidt het opsplitsen van de codering en voor elke code de omschrijving gebruiken zoals hierboven staat tot de juiste samengestelde omschrijving van de soort/aard zakelijk recht?
- kan de LV wel  de 2, 4 of 6 letter code naar 1, 2 of 3 2-lettercodes en deze vertalen naar enumeratiewaarden (bijvoorbeeld "EP" = "recht_van_erfpacht") of strings (bijvoorbeeld "EP" = "recht van erfpacht")?

**Comment by fsamwel** [comment]
voorstel van @CathyDingemanse is om dit veld eruit te halen. De stapeling van rechten moet uit de BRK API gehaald worden. (is comfort gegeven voor WOZ)

**Comment by JohanBoer** [comment]
Belanghebbende.soort is geen onderdeel meer van de specificatie. Deze issue is dus al eerder afgehandeld en wordt nu gesloten.
