### ISSUE TITLE
indicatieBezwaarBeroep over getoonde beschikking of over een beschikking?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#45]
Hoe gaan we om met de situatie dat een vorige bewoner bezwaar indient op een beschikking, en er voor de nieuwe bewoner er een beschikking is met meer recente ingangsdatum (op zelfde peiljaar)?

1. Wordt indicatieBezwaarBeroep=true (want er loopt een bezwaar tegen een beschikking op dit peiljaar) 
2. Of indicatieBezwaarBeroep=false (want het bezwaar betreft een andere beschikking dan die die getoond wordt)?

**Comment by fsamwel** [comment]
n.a.v. mijn vraag in https://github.com/VNG-Realisatie/Haal-Centraal-WOZ-bevragen/pull/39/#issuecomment-823375060

**Comment by CathyDingemanse** [comment]
Tjonge, ik zou zeggen dat we uitgaan van de meest recente beschikking. Voor die beschikking, en dus ook voor deze waarde geldt:   indicatieBezwaarBeroep=false.

De rationale hierachter is dat de meest recente beschikking de beste waarde is. Hiermee wordt bedoeld dat deze het meest overeenkomt met de werkelijke waarde.

**Comment by oversticht** [comment]
Niet _meest recente beschikking_ maar _meest recente waardepeildatum_ en _meest recente ingangsdatumWaarde_ zijn hier de norm.

Alleen de meest recente waardepeildatum wordt als actueel beschouwd. Als voor de meest recente waardepeildatum meerdere waarden bestaan zullen die verschillende ingangsdatumWaarde hebben. Daarvan wordt alleen de meest recente ingangsdatumWaarde als actueel beschouwd.

Voor die meest recente ingangsdatumWaarde kunnen wel meerdere belanghebbenden, en dus ook meerdere beschikkingen bestaan. Al die beschikkingen kunnen invloed hebben op de indicatieBezwaarBeroep, ongeacht of deze beschikkingen exact gelijktijdig zijn, of dat de ene beschikking iets recenter is dan de andere.

Nog lopende bezwaren voor een oudere waardepeildatum of voor een oudere ingangsdatumWaarde zijn irrelevant voor de indicatieBezwaarBeroep.

**Comment by CathyDingemanse** [comment]
> Voor die meest recente ingangsdatumWaarde kunnen wel meerdere belanghebbenden, en dus ook meerdere beschikkingen bestaan. Al die beschikkingen kunnen invloed hebben op de indicatieBezwaarBeroep, ongeacht of deze beschikkingen exact gelijktijdig zijn, of dat de ene beschikking iets recenter is dan de andere.
> 

@oversticht: om de indicatieBezwaarBeroep te bepalen moeten we alle beschikkingen (met de meest recente ingangsdatumWaarde op waardepeildatum x) afgaan om te kijken of er tenminste één bij is met een indicatieBezwaarBeroep?

**Comment by oversticht** [comment]
Dat is juist. Je moet van die beschikkingen de statusBelang raadplegen om de indicatieBezwaarBeroep op de juiste manier vast te stellen.

**Comment by fsamwel** [comment]
ik neem in de feature op: "indicatieBezwaarBeroep krijgt de waarde true wanneer ten minste één beschikking status van de betreffende WOZ-waarde **op peildatum en met de meest recente ingangsdatum** een van de volgende waarden heeft (...)"
