### ISSUE TITLE
lever lege waarden niet mee

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#47]
In de Haal Centraal API's hebben we afgesproken properties met leegwaarden (null of lege array of object waarin geen enkele property een waarde heeft)) niet te leveren. 

Ook worden indicatoren (booleans) alleen geleverd wanneer de waarde true is. Dit om te voorkomen dat berichten heel veel lege/niet relevante properties bevat.

Bijvoorbeeld in het antwoord hieronder zouden we properties geheimhoudingPersoonsgegevens, kvkNummer, rsin, vestigingsnummer, belanghebbendeGebruiker en kadastraalOnroerendeZaakIdentificaties niet opnemen in het antwoord.
```
    "belanghebbendeEigenaar": {
        "burgerservicenummer": "48",
        "geheimhoudingPersoonsgegevens": false,
        "kvkNummer": null,
        "naam": "Binnenhuis",
        "rsin": null,
        "type": "INP_BSN",
        "vestigingsnummer": null
    },
    "belanghebbendeGebruiker": null,
    "grondoppervlakte": 106,
    "identificatie": "000500055044",
    "kadastraalOnroerendeZaakIdentificaties": [],
```

Wat hier dan overblijft is de volgende response:
```
    "belanghebbendeEigenaar": {
        "burgerservicenummer": "48",
        "naam": "Binnenhuis",
        "type": "INP_BSN"
    },
    "grondoppervlakte": 106,
    "identificatie": "000500055044",
```

**Comment by fsamwel** [comment]
zie de (extreem korte) feature https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/indicatoren.feature

**Comment by fsamwel** [comment]
Postman valt nu op basis van de API specificaties over de null waarden. Bijvoorbeeld bij /wozobjecten/000000061120 krijg ik de volgende foutmeldingen in Postman:
The response body property "aanduiding.huisletter" should be string
The response body property "aanduiding.huisnummertoevoeging" should be string
The response body property "aanduiding.locatieomschrijving" should be string
The response body property "belanghebbendeEigenaar.kvkNummer" should be string
The response body property "belanghebbendeEigenaar.rsin" should be string
The response body property "belanghebbendeEigenaar.type" should be equal to one of the allowed values
The response body property "belanghebbendeEigenaar.vestigingsnummer" should be string
The response body property "belanghebbendeGebruiker" should be object

**Comment by fsamwel** [comment]
> Ook worden indicatoren (booleans) alleen geleverd wanneer de waarde true is. Dit om te voorkomen dat berichten heel veel lege/niet relevante properties bevat.

"geheimhoudingPersoonsgegevens": false wordt nu nog wel geleverd. Dat willen we niet, alleen wanneer "geheimhoudingPersoonsgegevens": true moet dit worden opgenomen.

**Comment by melsk-r** [comment]
@fsamwel Welke test gaf voorheen de fouten te zien op basis waarvan jij dit issue hebt opgevoerd? Ik heb een testgeval nodig waarvan ik weet dat sommige attributen een null waarde en sommige attributen de waarde 'false' bevatten.
Testen op /wozobjecten/000000061120 lukt iig niet meer omdat die resource niet bestaat.

@kad-tromps of heb jij voor mij een testgeval waarvoor dat geldt?
