### ISSUE TITLE
leveren externe links

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#54]

**Comment by fsamwel** [comment]
Bijvoorbeeld /wozobjecten/000500055046 geeft in _links:

```
        "adresseerbaarObjecten": {
            "href": "https://api.bag.test.kadaster.nl/esd/huidigebevragingen/v1/adresseerbareobjecten/{adresseerbaarObjectIdentificaties}",
            "templated": true
        },
        "panden": {
            "href": "https://api.bag.test.kadaster.nl/esd/huidigebevragingen/v1/panden/{pandIdentificaties}",
            "templated": true
        }
```
   

Volgens schema moeten dit arrays zijn.

**Comment by fsamwel** [comment]
Bijvoorbeeld /wozobjecten/000500055044 bevat geen waarden voor belanghebbendeGebruiker.burgerservicenummer. Toch is de link als template opgenomen:
```
        "belanghebbendeGebruiker": {
            "href": "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/{belanghebbendeGebruiker_burgerservicenummer}",
            "templated": true
        },
```

Ook is er een link kadastraalOnroerendeZaken opgenomen, terwijl geen kadastraalOnroerendeZaakIdentificaties zijn. Idem voor de link panden (er zijn geen pandIdentificaties)

**Comment by fsamwel** [comment]
de link adres verwijst naar de testomgeving van BAG. Dat is niet de juiste, gebruikers kunnen de BAG productieomgeving gebruiken. De testomgeving wordt door het BAG ontwikkelteam gebruikt om te testen en is dus niet stabiel.

Dus in plaats van 
        "adres": {
            "href": "https://api.bag.test.kadaster.nl/esd/huidigebevragingen/v1/adressen/0200200000054860"
        },
is het beter te verwijzen naar
        "adres": {
            "href": "https://api.bag.kadaster.nl/esd/huidigebevragingen/v1/adressen/0200200000054860"
        },

**Comment by fsamwel** [comment]
@kad-tromps in /wozobjecten/800000051111 is de belanghebbendeEigenaar en de belanghebbendeGebruiker een niet-natuurlijk persoon. Toch verwijst de link-template naar de BRP, dus naar natuurlijk personen:
        "belanghebbendeEigenaar": {
            "href": "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/{belanghebbendeEigenaar_burgerservicenummer}",
            "templated": true
        },
        "belanghebbendeGebruiker": {
            "href": "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/{belanghebbendeGebruiker_burgerservicenummer}",
            "templated": true
        }

Voor niet-natuurlijk personen moet de link naar HR verwijzen. Helaas is er (nog) geen (Haal Centraal of andere) HR API beschikbaar waarnaar je zou kunnen verwijzen. Dus in dit geval zou je geen link kunnen opnemen

**Comment by fsamwel** [comment]
de template voor belanghebbendeEigenaar en belanghebbendeGebruiker gebruikt nu een underscore i.p.v. een punt. Dat is niet in lijn met hoe het in de andere Haal Centraal API's is gedaan. Dat is denk ik niet handig voor gebruikers.

Als dit niet lukt, wellicht niet als template aanbieden (afgezien van eventueel templated base url voor de externe API).

@MelvLee hoe denk jij hierover? Is het een probleem dat in WOZ de template met underscore als separator de verwijzing naar een property opbouwt?

**Comment by MelvLee** [comment]
Nee, dit is geen probleem. Zowel punt als underscore kunnen worden gebruikt in de naam van de placeholder.

**Comment by fsamwel** [comment]
Oke dan laten we het zo. Dan moet er alleen wel een specifieke feature worden gemaakt die beschrijft hoe dit voor WOZ werkt (afwijkend van hoe het in common staat). @MelvLee kan jij dat maken?

**Comment by fsamwel** [comment]
@MelvLee ik heb hiervoor issue #85 gemaakt

**Comment by fsamwel** [comment]
@kad-tromps soms wordt belanghebbendeEigenaar als volledige url geleverd en belanghebbendeGebruiker templated, en soms andersom. Zit daar logica achter?

/wozobjecten/000500055044 heeft in _links:
```
        "belanghebbendeEigenaar": {
            "href": "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/000000048"
        },
        "belanghebbendeGebruiker": {
            "href": "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/{belanghebbendeGebruiker_burgerservicenummer}",
            "templated": true
        },
```

/wozobjecten/000500030828 heeft in _links:
```
        "belanghebbendeEigenaar": {
            "href": "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/{belanghebbendeEigenaar_burgerservicenummer}",
            "templated": true
        },
        "belanghebbendeGebruiker": {
            "href": "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/000000012"
        },
```

N.B. bij 000500055044 is de eigenaar een natuurlijk persoon en is er geen gebruiker, bij 000500030828 is de eigenaar een niet-natuurlijk persoon en de gebruiker een natuurlijk persoon. Het lijkt er haast op dat, wanneer er geen burgerservicenummer is, de templated link wordt geleverd met template voor burgerservicenummer.

**Comment by kad-tromps** [comment]
> de template voor belanghebbendeEigenaar en belanghebbendeGebruiker gebruikt nu een underscore i.p.v. een punt. Dat is niet in lijn met hoe het in de andere Haal Centraal API's is gedaan. Dat is denk ik niet handig voor gebruikers.
> 
> Als dit niet lukt, wellicht niet als template aanbieden (afgezien van eventueel templated base url voor de externe API).
> 
> @MelvLee hoe denk jij hierover? Is het een probleem dat in WOZ de template met underscore als separator de verwijzing naar een property opbouwt?

Ik had deze al besproken met Melvin. De 'punt' is een gereserveerde character in templated fields (staat voor domain expansion, dus als je een lijst variable=[www, url, nl] hebt, zou .variable naar www.ur.nl moeten resolven). Daarom is er gekozen voor een underscore

**Comment by kad-tromps** [comment]
> @kad-tromps soms wordt belanghebbendeEigenaar als volledige url geleverd en belanghebbendeGebruiker templated, en soms andersom. Zit daar logica achter?
> 
> /wozobjecten/000500055044 heeft in _links:
> 
> ```
>         "belanghebbendeEigenaar": {
>             "href": "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/000000048"
>         },
>         "belanghebbendeGebruiker": {
>             "href": "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/{belanghebbendeGebruiker_burgerservicenummer}",
>             "templated": true
>         },
> ```
> 
> /wozobjecten/000500030828 heeft in _links:
> 
> ```
>         "belanghebbendeEigenaar": {
>             "href": "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/{belanghebbendeEigenaar_burgerservicenummer}",
>             "templated": true
>         },
>         "belanghebbendeGebruiker": {
>             "href": "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/000000012"
>         },
> ```
> 
> N.B. bij 000500055044 is de eigenaar een natuurlijk persoon en is er geen gebruiker, bij 000500030828 is de eigenaar een niet-natuurlijk persoon en de gebruiker een natuurlijk persoon. Het lijkt er haast op dat, wanneer er geen burgerservicenummer is, de templated link wordt geleverd met template voor burgerservicenummer.

ja, precies. Aangezien er voor nu alleen een link is voor burgerservice nummer, geven we een template terug als er geen burgerservice nummer is, omdat de belanghebbende geen natuurlijk persoon is, of omdat het veld er niet is. Maar, zoals in een eerdere opmerking gezegd, gaan we gewoon links weg laten waar geen veld voor beschikbaar is

**Comment by kad-tromps** [comment]
> Bijvoorbeeld /wozobjecten/000500055046 geeft in _links:
> 
> ```
>         "adresseerbaarObjecten": {
>             "href": "https://api.bag.test.kadaster.nl/esd/huidigebevragingen/v1/adresseerbareobjecten/{adresseerbaarObjectIdentificaties}",
>             "templated": true
>         },
>         "panden": {
>             "href": "https://api.bag.test.kadaster.nl/esd/huidigebevragingen/v1/panden/{pandIdentificaties}",
>             "templated": true
>         }
> ```
> 
> Volgens schema moeten dit arrays zijn.

Ik had dit eerder met @MelvLee besproken, en daar kwamen we tot de conclusie dat we deze templated willen laten, zodat de links niet te lang worden, moet dit wel blijven? Of moeten we in de array ook alle bijbehorende identificaties geven?

**Comment by MelvLee** [comment]
@kad-tromps, er ligt een design keuze hieronder. Dit is niet bekend bij jou, waardoor het niet duidelijk is waarom er hier voor een array als type is gekozen.
Als een provider links teruggeeft, dan kan hij kiezen of hij de links templated of niet teruggeeft. Templated is vooral handig als er veel subresources zijn. Als er maar enkele (1, 2 of 3) subresources zijn, is het (denken we) makkelijker om niet templated terug te geven. We willen dus beide situaties ondersteunen, en dat is de reden waarom we gekozen hebben om de links altijd als array types te definieren.
