### ISSUE TITLE
zoeken WOZ objecten

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#56]

**Comment by kad-tromps** [comment]
Deze wordt per ingang opgepakt. Deze sprint is zoeken op RSIN opgeleverd, andere endpoints volgen.

**Comment by kad-tromps** [comment]
Ik zag de pattern restricties niet terug op de jabber pagina, alleen in de openapi.yaml specificatie. Ik heb er daar door niet aan gedacht restricties te leggen op huisletter en huisnummer toevoeging, zal deze ook toevoegen. Daar heb ik echter wel een paar opmerkingen over de regex

postcode: ^[1-9][0-9][0-9][0-9][A-Z][A-Z]$ is equivalent aan ^[1-9][0-9]{3}[A-Z]{2}$, en deze heb ik dan ook gebruikt
huisletter: ^[a-zA-Z]{1}$ is equivalent aan ^[a-zA-Z]$. Een count van 1 is impliciet

**Comment by fsamwel** [comment]
> postcode: ^[1-9][0-9][0-9][0-9][A-Z][A-Z]$ is equivalent aan ^[1-9][0-9]{3}[A-Z]{2}$, en deze heb ik dan ook gebruikt
huisletter: ^[a-zA-Z]{1}$ is equivalent aan ^[a-zA-Z]$. Een count van 1 is impliciet

@JohanBoer had jij een reden om de regex zo op te stellen als je gedaan hebt? Ik denk dat de suggesties van @kad-tromps wel de beter leesbare varianten zijn.

**Comment by JohanBoer** [comment]
Er zijn meerdere wegen naar Rome. Zoals @kad-tromps zegt: ze zijn equivalent. Ik heb geen voorkeur en zal de voorstellen van Stijn overnemen in de specs.
