### ISSUE TITLE
lever instance in problem+json als absolute link

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#59]
In de specificaties voor problem+json is instance gedefinieerd met format: uri.

Verschillende tooling, zoals Postman geeft hierop een foutmelding, wanneer een relatieve link wordt geleverd. Formeel is het denk ik niet fout om een relatieve link te leveren, maar wellicht toch beter absolute link te leveren (om een foutmelding in Postman te voorkomen)?

**Comment by fsamwel** [comment]
@kad-reinda @kad-tromps @kad-verstp de url wordt nu wel geleverd, maar is niet correct. Bijvoorbeeld bij request "https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten/000500055044?fields=bestaatniet" krijg ik "instance": "http://api.acceptatie.kadaster.nl/haalcentraal-api/wozobjecten/000500055044?fields=bestaatniet".

**Comment by kad-tromps** [comment]
> @kad-reinda @kad-tromps @kad-verstp de url wordt nu wel geleverd, maar is niet correct. Bijvoorbeeld bij request "https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten/000500055044?fields=bestaatniet" krijg ik "instance": "http://api.acceptatie.kadaster.nl/haalcentraal-api/wozobjecten/000500055044?fields=bestaatniet".

Dit zou nu weer goed moeten staan @fsamwel We zullen hier scherp op zijn, maar mocht deze discrepantie zich weer voor doen, zou je ons een direct berichtje kunnen sturen? (mail of slack). Dit is namelijk een configuratie die we helaas apart in de kadaster api portal én in onze deployment gelijk moeten houden, dus dit kan buiten ontwikkeling ook voorkomen.

**Comment by fsamwel** [comment]
@kad-reinda @kad-tromps @kad-verstp ik krijg niet de goede url. 
Bijvoorbeeld https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten/12345678901 geeft:
"instance": "http://api.acceptatie.kadaster.nl/haalcentraal-api/wozobjecten/12345678901"

**Comment by fsamwel** [comment]
Dat is trouwens ook het geval bij een goed antwoord in de self link.
Bijvoorbeeld https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten/000500055044 geeft:
```
    "_links": {
        "self": {
            "href": "http://api.acceptatie.kadaster.nl/haalcentraal-api/wozobjecten/000500055044"
        },
```

**Comment by fsamwel** [comment]
@kad-reinda @kad-tromps @kad-verstp @kad-leenec ik krijg nog "http" in de self en instance i.p.v. "https"

Bijvoorbeeld GET https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten/000500055044 geeft:
"self": {"href": "http://api.acceptatie.kadaster.nl/haalcentraal-api/wozobjecten/000500055044"}

Bijvoorbeeld GET https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten/000500055044?fields=bestaatniet geeft:
"instance": "http://api.acceptatie.kadaster.nl/haalcentraal-api/wozobjecten/000500055044?fields=bestaatniet"

**Comment by kad-tromps** [comment]
Het verschil tussen de urls komt omdat we een klein stukje in de URL vervangen om limitaties in de routing te omzeilen. In dit geval is dit api.acceptatie.kadaster.nl/{router_prefix}/wozobjecten/..., waar router_prefix lvwoz/api/v1 zou moeten zijn, maar haalcentraal-api is. Dit is een configuratie, en eenvoudig te fixen. Het omzetten van https naar http moet ik even wat dieper naar kijken, aangezien we bij aankomst van de server deze informatie kwijt zijn.

**Comment by kad-tromps** [comment]
We hebben het http/https issue geanalyseerd, en dit lijkt nog vrij lastig te zijn. In principe word al het http verkeer naar de server geredirect naar https, dus het gedrag van de link volgen zal niet veel veranderen. Daarom wil ik voorstellen om de routing prefix te fixen (/haalcentraal-api -> /lvwoz/api/v1), en verder de self link laten zoals het nu is.

**Comment by MelvLee** [comment]
Omdat jullie gateway alle requests toch redirect naar https, is het dan niet beter om voor alle urls in de response https als protocol te gebruiken?

**Comment by kad-tromps** [comment]
Het is juist het aanpassen van het protocol dat lastig is. Ik bedoel, alles kan, maar we gaan enorm afwijken van het HAL framework

**Comment by kad-tromps** [comment]
Als het goed is werkt dit nu op de nieuwe URL die Axel heeft verstuurd
