### ISSUE TITLE
self link bij gebruik van fields ongelijk aan het request

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#66]
GET 'https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten/000500055044?fields=adresseerbaarObjectIdentificaties,grondoppervlakte'

dit levert in het antwoord:
    "_links": {
        "self": {
            "href": "http://api.acceptatie.kadaster.nl/wozobjecten/000500055044?fields=adresseerbaarObjectIdentificaties&fields=grondoppervlakte"
        }
    }

De verschillende waarden in fields zijn opgesplitst in verschillende voorkomens van de fields parameter. De waarde in _links.self.href moet identiek zijn aan het request

**Comment by melsk-r** [comment]
De verschillende waarden in fields zijn niet meer opgesplitst over verschillende voorkomens van de fields parameter. Dit probleem is dus opgelost.
