### ISSUE TITLE
vragen om _links met fields parameter geeft fout

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#67]
GET 'https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten/000500055044?fields=_links' geeft een foutmelding:

```
{
    "type": "https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1",
    "title": "Een of meerdere parameters zijn niet correct.",
    "detail": "Parameter 'fields' bevat een (deels) ongeldige waarde",
    "instance": "/wozobjecten/000500055044",
    "status": 400,
    "invalidParams": {
        "reason": "ongeldige waarde: '_links' opgegeven",
        "name": "fields",
        "code": "fields"
    },
    "code": "paramsValidation"
}
```

_links is een property in de response, dus zou geen foutmelding moeten geven (ook al wordt die altijd geleverd)

Plus  invalidParams is volgens schema een array, maar in de response is het object direct opgenomen: #69

**Comment by fsamwel** [comment]
@kad-tromps bij vragen met fields=_links krijg ik nu geen foutmelding meer. Maar ik krijg alleen de self link, niet de andere links.

Bijvoorbeeld:
{
    "_links": {
        "self": {
            "href": "http://api.acceptatie.kadaster.nl/haalcentraal-api/wozobjecten/000500055044?fields=_links"
        }
    }
}

Hier had ik alle links verwacht:
{
    "_links": {
        "self": {
            "href": "http://api.acceptatie.kadaster.nl/haalcentraal-api/wozobjecten/000500055044?fields=_links"
        },
        "adres": {
            "href": "https://api.bag.test.kadaster.nl/esd/huidigebevragingen/v1/adressen/0200200000054860"
        },
        "adresseerbaarObjecten": [
            {
                "href": "https://api.bag.test.kadaster.nl/esd/huidigebevragingen/v1/adresseerbareobjecten/{adresseerbaarObjectIdentificaties}",
                "templated": true
            }
        ],
        "belanghebbendeEigenaar": {
            "href": "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/000000048"
        }
    }
}

**Comment by fsamwel** [comment]
wanneer ik specifiek vraag om een van de links, kadastraalOnroerendeZaken, krijg ik een foutmelding:
```
{
    "type": "https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.5.1",
    "title": "Interne server fout.",
    "status": 500,
    "detail": "The server encountered an unexpected condition which prevented it from fulfilling the request.",
    "instance": "http://api.acceptatie.kadaster.nl/haalcentraal-api/wozobjecten/000500055044?fields=_links.kadastraalOnroerendeZaken"
}
```

**Comment by kad-leenec** [comment]
@fsamwel Bovenstaande bevinding is opgepakt en binnenkort door jou te testen. 
We zijn druk bezig met het afvangen van mogelijke parameters met de diverse waarden. Hier liepen wij echter tegen een foutmelding aan door in het request bijvoorbeeld het volgende in voeren: ?fields=_links,_links.adres.
Onze code split de 2 'fields' en maakt hier een key voor. Echter '_links' komt 2x voor dus in onze collectie ontstaat een 'duplicate key' error. Onze vraag is nu of deze situatie voor kan komen aangezien je met ?fields='_links' alle relaties al ophaalt.
