### ISSUE TITLE
url van self link niet correct (o.a. http i.p.v. https)

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#76]
https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten?rsin=020664606

bevat:
    "_links": {
        "self": {
            "href": "http://api.acceptatie.kadaster.nl/haalcentraal-api/wozobjecten?rsin=020664606"
        }
    }

De base url is niet correct:
- http i.p.v. https
- "haalcentraal-api" i.p.v. "lvwoz/api/v1"

Idem in de self link van gevonden wozobjecten:
```
                "_links": {
                    "self": {
                        "href": "http://api.acceptatie.kadaster.nl/haalcentraal-api/wozobjecten/800000051111"
                    }
```

En in de self link bij het raadplegen van een WOZ-object. Bijvoorbeeld https://api.acceptatie.kadaster.nl/lvwoz/api/v1/wozobjecten/000500055044 geeft:
```
    "_links": {
        "self": {
            "href": "http://api.acceptatie.kadaster.nl/haalcentraal-api/wozobjecten/000500055044"
        },
```

**Comment by melsk-r** [comment]
> http i.p.v. https
Nu staat overal 'https'

De logica achter de te gebruiken baseurl ontgaat me eerlijk gezegd. 
Daar worstel ik in #123 , #124 , #125 en #126 ook mee. Wellicht kan daar wat duidelijkheid in verschaft worden zodat ik beter kan beoordelen of dit issue helemaal opgelost is.

**Comment by kad-tromps** [comment]
@melsk-r ik heb deze ticket geanalyseerd en we zijn druk bezig met een oplossing, zodat het genereren van _self links rekening houd met `x-forwarded` headers, oftewel waar we origineel vandaan zijn gekomen. Als het goed is word hiermee #123, #124 en #126 opgelost.

 De links in #125 worden niet gegenereerd, deze komen uit configuratie. Als jij een specificatie hebt van wat deze externe links moeten zijn voor de verschillende omgevingen FTO, ETO en PROD (of gewoon voor test en prod) dan kan ik deze correct af configureren.

**Comment by melsk-r** [comment]
> Als jij een specificatie hebt van wat deze externe links moeten zijn voor de verschillende omgevingen FTO, ETO en PROD (of gewoon voor test en prod) dan kan ik deze correct af configureren.

@kad-tromps In [issue 54](https://github.com/VNG-Realisatie/Haal-Centraal-WOZ-bevragen/issues/54) doet @fsamwel  volgens mij een voorstel. Hij specificeert daar echter niet per omgeving (FTO, ETO en PROD) hoe de links er uit moeten zien. Zijn voorstel komt op het volgende neer:
* voor de BAG mag gebruik gemaakt kan worden van https://api.bag.kadaster.nl/esd/huidigebevragingen/v1
* voor de BRK van https://api.brk.kadaster.nl/esd-eto-apikey/bevragen/v1/

**Comment by JohanBoer** [comment]
Bij het testen in de ETO omgeving starten de terugontvangen urls allemaal met 'https' probleem lijkt me dus opgelost.

Aangezien dit volgens mij een configuratie dingetje is weet ik niet of dit ook in andere omgevingen dan ETO opgelost is.
