### ISSUE TITLE
zoekresultaat wozobjecten i.p.v. wozObjecten

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#79]
Het zoekresultaat wordt nu geplaats in     "_embedded": { "wozobjecten": [ ... ] }

Volgens het API schema zou dit moeten zitten in "_embedded": { "wozObjecten": [ ... ] }

(dus hoofdletter "O" voor Objecten)

**Comment by melsk-r** [comment]
Fout is opgelost. Zoekresultaten worden nu in "_embedded": { "wozObjecten": [ ... ] } getoond.
