### ISSUE TITLE
addresseerbaarObjecten moet zijn adresseerbareObjecten

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#80]
In WozObjectBasisLinks zit een link "adresseerbaarObjecten". In BAG heet dit "adresseerbareObjecten".

Lijkt mij goed dit dan hier hetzelfde te noemen als in BAG

**Comment by fsamwel** [comment]
@JohanBoer wanneer je dit gecorrigeerd hebt, zou je dit issue willen assignet aan @kad-tromps, @kad-verstp en @kad-reinda en het in Ready for sprint zetten

**Comment by JohanBoer** [comment]
Ik heb deze toegevoegd aan een openstaande pull -request.Die had ik gedaan vanuit mijn master (slordig) dus akn deze mee.  @fsamwel Zou jij ook #82 kunnen reviewen ? Dan kan deze mee.

**Comment by JohanBoer** [comment]
Deze is correct geïmplementeerd. Issue wordt gesloten.
