### ISSUE TITLE
link naar kadastraalOnroerendeZaken niet gedefinieerd

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#81]
In WozObjectBasisLinks is geen link naar kadastraalOnroerendeZaken opgenomen. Deze zou ik wel verwachten, er is immers ook een identificatie van de relatie kadastraalOnroerendeZaakIdentificaties.

**Comment by fsamwel** [comment]
@JohanBoer als je deze aanpassing gedaan hebt, wil je dit issue dan in Ready for sprint zetten en toewijzen aan @kad-tromps, @kad-verstp en @kad-reinda

**Comment by fsamwel** [comment]
De link is nu al wel gemaakt, maar geleverd als object i.p.v. als array. Ik neem aan dat je dit als array gaat definiëren, omdat ook kadastraalOnroerendeZaakIdentificaties een array is. Dit moet dus ook worden gecorrigeerd in de implementatie

**Comment by JohanBoer** [comment]
Link is nu opgenomen als array. Ook deze is onderdeel van PR #82 en wordt meegenomen bij het mergen. Ik zet deze pas op ready for sprint als de PR gemerged is.

**Comment by JohanBoer** [comment]
Deze is nu correct geïmplementeerd en wordt gesloten.
