### ISSUE TITLE
naam van natuurlijk persoon wordt alleen achternaam getoond

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#83]
bijvoorbeeld /wozobjecten/000500055044

```
    "belanghebbendeEigenaar": {
        "burgerservicenummer": "000000048",
        "geheimhoudingPersoonsgegevens": true,
        "naam": "Binnenhuis",
        "type": "natuurlijk_persoon"
    }
```

Voor een natuurlijk persoon is het de bedoeling dat hier de volledige naam getoond wordt, zoals het example "Jan de Vries" toont. In de testdata is dit steeds één woord, wat suggereert dat dit alleen de geslachtsnaam is.

**Comment by melsk-r** [comment]
@fsamwel Er wordt nu 'T. van Binnenhuis' getoond, dus alleen de eerste letter van de voornaam i.p,.v. de gehele voornaam zoals in het example. Is dat zoals gewenst?

**Comment by kad-verstp** [comment]
@melsk-r @fsamwel @kad-tromps 

In de xml WOZ berichten, waarmee de database wordt gevuld, worden alleen voorletters meegegeven niet een hele voornaam en krijg je het ook niet terug in het antwoord json

**Comment by melsk-r** [comment]
@kad-reinda @kad-tromps @kad-verstp Ik haal jullie ven van de lijst met assignees af. We (HC team) gaan bepalen of dit voldoende voor ons is.

**Comment by JohanBoer** [comment]
Aangepast met PR #180
