### ISSUE TITLE
waarden niet aflopend gesorteerd op waardepeildatum en ingangsdatum

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#86]
In [waarden.feature](https://github.com/VNG-Realisatie/Haal-Centraal-WOZ-bevragen/blob/master/features/waarden.feature) staat:
> N.B. De API levert waarden aflopend gesorteerd op waardepeildatum en daarbinnen op ingangsdatum.

Nu worden waarden oplopend gesorteerd op waardepeildatum geleverd

**Comment by fsamwel** [comment]
@MelvLee maakt dit iets uit voor jou? De proxy die je maakt kan/zal dit immers toch ook sorteren.

**Comment by MelvLee** [comment]
Het is geen probleem om in de proxy anders te sorteren
