### ISSUE TITLE
ligplaats en standplaats niet opgenomen in adresseerbaarObjectIdentificaties

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#87]
Volgens https://github.com/VNG-Realisatie/Haal-Centraal-WOZ-bevragen/issues/60#issuecomment-848507334 is WOZ-object:
> Ligplaats: 800000200021
> Standplaats: 800000200022

/wozobjecten/800000200021 en /wozobjecten/800000200022 hebben in het antwoord geen property "adresseerbaarObjectIdentificaties" en ook in "_links" geen "adresseerbaarObjecten"

**Comment by kad-tromps** [comment]
@kad-reinda @kad-verstp volgensmij hebben stand en ligplaatsen alleen ontleent aanduiding aan? We zoeken momenteel alleen in is verbonden met, aangezien ontleent aanduiding aan vaak niks met het WOZ object te maken heeft. Moeten we deze wel tonen?

**Comment by fsamwel** [comment]
Heeft dit ook te maken met de openstaande vraag over de definitie van adresseerbaarObjectIdentificatie?

```
- name: adresseerbaarObjectIdentificatie
          in: query
          description: Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is of waar het object zijn aanduiding aan ontleent
```
versus
```
        adresseerbaarObjectIdentificaties:
          type: array
          description: "BAG identificaties van verblijfsobjecten, standplaatsen en ligplaatsen die aan dit WOZ-object verbonden zijn."
```

Dit is inmiddels in de specificaties recht getrokken ("of waar het object zijn aanduiding aan ontleent" verwijderd). @JohanBoer is de conclusie inderdaad dat we adresseerbare objecten alleen moeten zoeken op verbonden met? In dat geval moet https://github.com/VNG-Realisatie/Haal-Centraal-WOZ-bevragen/blob/master/features/zoeken.feature ook worden aangepast.

@kad-verstp betekent dit dat de testdata moet worden aangepast zodat Ligplaats: 800000200021 en Standplaats: 800000200022 verbonden zijn met een WOZ-object, i.p.v. alleen via de aanduiding? Zie 
https://github.com/VNG-Realisatie/Haal-Centraal-WOZ-bevragen/issues/60#issuecomment-848507334

**Comment by JohanBoer** [comment]
> @JohanBoer is de conclusie inderdaad dat we adresseerbare objecten alleen moeten zoeken op verbonden met? In dat geval moet

Volgens mij hebben we deze conclusie inderdaad in een sessie getrokken en heb ik naar aanleiding daarvan de description aangepast.

**Comment by kad-verstp** [comment]
Ligplaats: 000500035010
Standplaats: 000500035020

Die een AOTOND relatie hebben ( Is verbonden met) Hiervan is wel het adresseerbaarObjectIdentificaties te zien
