### ISSUE TITLE
Paginering van zoekresultaten

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#99]

**Comment by fsamwel** [comment]
@kad-tromps @kad-verstp @kad-reinda hebben we een zoekvraag die voldoende zoekresultaten teruggeeft om paginering te zien?

**Comment by fsamwel** [comment]
@kad-tromps @kad-verstp @kad-reinda hebben we een zoekvraag die voldoende zoekresultaten teruggeeft om paginering te zien? Ik heb alleen enkele zoekingangen gevonden die 2 WOZ objecten vinden, maar dat is niet genoeg om paginering in werking te zien

**Comment by MelvLee** [comment]
@fsamwel, is het niet voldoende om paging te testen door de pageSize op 1 te zetten?

**Comment by kad-leenec** [comment]
@fsamwel wat is de huidige status van dit ticket?

**Comment by fsamwel** [comment]
ik denk dat je dan wel een heel erg beperkte test doet. We kunnen dan vaststellen dat er paginering is en dat de pagineringlinks op de juiste manier worden samengesteld. Al het andere niet. En als dit ook data is waarmee clients hun applicatie kunnen testen/demo-en is het ook te beperkt.

**Comment by fsamwel** [comment]
@kad-tromps tijdens de demo net had je een zoekvraag met kvknummer met pageSize=2 die 3 pagina's opleverde (als ik het goed zag). Bij welk kvknummer kreeg je hiervoor genoeg resultaten?
